### ISSUE TITLE
0.9 Todo

### ISSUE THREAD

**Issue by manuphatak** [bionikspoon/pureyaml#1]
- [x] Serialize basic data types
- [x] Serialize most use cases
- [x] Deserialize basic data types
- [x] Deserialize most use cases
- [ ] Write docs
- [ ] Add more tests based on yaml.org specs
- [x] Read and Write to open file objects
- [x] Dump kw flags, `sort` and `indent`
- [x] Clear TODOs
- [x] Basic `ply` config optimization

**Comment by manuphatak** [comment]
80 % of expected use cases for the parser, encoder, and decoder are complete.  They're tested, sanity tested, and tested against `PyYaml` for consistency.  There's a few notable deviations from pyyaml, for example, we're not supporting "flow" style output for now.

### 80 % of expected use cases:
- sequences
- maps
- scalars
- implicit data types (floats, strings, ints, bools, none, binary)
- explicit data casting ie `!!str`, double quotes, single quotes
- binary, string literals, string folding
- a variety of quirky rules for these ie compact sequence starts, no indent for maps of sequences, optional indents, 

**Notably missing**
- Purely empty scalars.
  
  Empty double/single quotes works. Null values work.  But genuinely missing  values has been completely toxic to the parser setup.   It's not impossible, it's just not very interesting right now.

### Not in the 80 %
- omaps, sets, tuples, custom tags (ie `!myobject`), directives, explicit tags, anchors and references. 
  
  Some of these will be easier then others.  For now they're a lower priority, and scheduled for future releases.

**Comment by manuphatak** [comment]
I've spend some time on automating the test suite.  There's 2 main test groups, 1 for each encoding and decoding.  

The decoder test group takes a block of yaml text and tests it against the node parser, the decode (load) function, and `pyyaml`'s load function to safeguard consistency, and a sanity check (text -> obj1 -> text -> obj2, `assert obj1 == obj2`)

The encoder is practically the same in the other direction, it starts with a python object and tests nodes/text/sanity/pyyaml.

Including a ton of duplicates (original tests; probably about 100), there's almost 500 tests, with over 100 unique examples. 

The testing is real.
