### ISSUE TITLE
1.0 Todo

### ISSUE THREAD

**Issue by manuphatak** [bionikspoon/pureyaml#2]
- [ ] profile a few scenarios
- [ ] optimize tokens
- [ ] optimize parser
- [ ] optimize node visitors
- [ ] optimize string operations
- [ ] sync up public api with `PyYaml`
- [ ] support anchors and references
- [ ] support all builtin tags
  - [ ] set
  - [ ] omap
  - [ ] other
- [ ] support explicit tags with `<` and `>` indicators
- [ ] support directives
- [ ] support `python/...` tag objects, from `PyYaml` specs`
- [ ] support custom user created tags
- [ ] parse and ignore directives
