### ISSUE TITLE
1.1 Todo

### ISSUE THREAD

**Issue by manuphatak** [bionikspoon/pureyaml#3]
- [ ] Support more of `PyYaml`s features
- [ ] Conform to yaml.org's pipeline specs
- [ ] Support serializing and deserializing, custom objects
